apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service-cfgmp
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: 10.100.181.20
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-db-sec
type: Opaque
data:
  dGhlIHBhc3N3b3Jk
