apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-sec
type: Opaque
data:
  <THE KEY FROM Secret WHICH has THE ENCODED PASSWORD>: <OUTPUT OF `echo -n 'the password' | base64`>
